# CMake generated Testfile for 
# Source directory: /home/eddie/Documents/kodi
# Build directory: /home/eddie/Documents/kodi-build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TestVideoInfoScanner.VideoInfoScanner "kodi-test" "--gtest_filter=VideoInfoScanner*")
add_test(TestCryptThreadingInitializer.General "kodi-test" "--gtest_filter=TestCryptThreadingInitializer.General")
add_test(TestXMLUtils.GetHex "kodi-test" "--gtest_filter=TestXMLUtils.GetHex")
add_test(TestXMLUtils.GetUInt "kodi-test" "--gtest_filter=TestXMLUtils.GetUInt")
add_test(TestXMLUtils.GetLong "kodi-test" "--gtest_filter=TestXMLUtils.GetLong")
add_test(TestXMLUtils.GetFloat "kodi-test" "--gtest_filter=TestXMLUtils.GetFloat")
add_test(TestXMLUtils.GetDouble "kodi-test" "--gtest_filter=TestXMLUtils.GetDouble")
add_test(TestXMLUtils.GetInt "kodi-test" "--gtest_filter=TestXMLUtils.GetInt")
add_test(TestXMLUtils.GetBoolean "kodi-test" "--gtest_filter=TestXMLUtils.GetBoolean")
add_test(TestXMLUtils.GetString "kodi-test" "--gtest_filter=TestXMLUtils.GetString")
add_test(TestXMLUtils.GetAdditiveString "kodi-test" "--gtest_filter=TestXMLUtils.GetAdditiveString")
add_test(TestXMLUtils.GetStringArray "kodi-test" "--gtest_filter=TestXMLUtils.GetStringArray")
add_test(TestXMLUtils.GetPath "kodi-test" "--gtest_filter=TestXMLUtils.GetPath")
add_test(TestXMLUtils.GetDate "kodi-test" "--gtest_filter=TestXMLUtils.GetDate")
add_test(TestXMLUtils.GetDateTime "kodi-test" "--gtest_filter=TestXMLUtils.GetDateTime")
add_test(TestXMLUtils.SetString "kodi-test" "--gtest_filter=TestXMLUtils.SetString")
add_test(TestXMLUtils.SetAdditiveString "kodi-test" "--gtest_filter=TestXMLUtils.SetAdditiveString")
add_test(TestXMLUtils.SetStringArray "kodi-test" "--gtest_filter=TestXMLUtils.SetStringArray")
add_test(TestXMLUtils.SetInt "kodi-test" "--gtest_filter=TestXMLUtils.SetInt")
add_test(TestXMLUtils.SetFloat "kodi-test" "--gtest_filter=TestXMLUtils.SetFloat")
add_test(TestXMLUtils.SetBoolean "kodi-test" "--gtest_filter=TestXMLUtils.SetBoolean")
add_test(TestXMLUtils.SetHex "kodi-test" "--gtest_filter=TestXMLUtils.SetHex")
add_test(TestXMLUtils.SetPath "kodi-test" "--gtest_filter=TestXMLUtils.SetPath")
add_test(TestXMLUtils.SetLong "kodi-test" "--gtest_filter=TestXMLUtils.SetLong")
add_test(TestXMLUtils.SetDate "kodi-test" "--gtest_filter=TestXMLUtils.SetDate")
add_test(TestXMLUtils.SetDateTime "kodi-test" "--gtest_filter=TestXMLUtils.SetDateTime")
add_test(TestXBMCTinyXML.ParseFromString "kodi-test" "--gtest_filter=TestXBMCTinyXML.ParseFromString")
add_test(TestXBMCTinyXML.ParseFromFileHandle "kodi-test" "--gtest_filter=TestXBMCTinyXML.ParseFromFileHandle")
add_test(TestVariant.VariantTypeInteger "kodi-test" "--gtest_filter=TestVariant.VariantTypeInteger")
add_test(TestVariant.VariantTypeUnsignedInteger "kodi-test" "--gtest_filter=TestVariant.VariantTypeUnsignedInteger")
add_test(TestVariant.VariantTypeBoolean "kodi-test" "--gtest_filter=TestVariant.VariantTypeBoolean")
add_test(TestVariant.VariantTypeString "kodi-test" "--gtest_filter=TestVariant.VariantTypeString")
add_test(TestVariant.VariantTypeWideString "kodi-test" "--gtest_filter=TestVariant.VariantTypeWideString")
add_test(TestVariant.VariantTypeDouble "kodi-test" "--gtest_filter=TestVariant.VariantTypeDouble")
add_test(TestVariant.VariantTypeArray "kodi-test" "--gtest_filter=TestVariant.VariantTypeArray")
add_test(TestVariant.VariantTypeObject "kodi-test" "--gtest_filter=TestVariant.VariantTypeObject")
add_test(TestVariant.VariantTypeNull "kodi-test" "--gtest_filter=TestVariant.VariantTypeNull")
add_test(TestVariant.VariantFromMap "kodi-test" "--gtest_filter=TestVariant.VariantFromMap")
add_test(TestVariant.operatorTest "kodi-test" "--gtest_filter=TestVariant.operatorTest")
add_test(TestVariant.push_back "kodi-test" "--gtest_filter=TestVariant.push_back")
add_test(TestVariant.append "kodi-test" "--gtest_filter=TestVariant.append")
add_test(TestVariant.c_str "kodi-test" "--gtest_filter=TestVariant.c_str")
add_test(TestVariant.swap "kodi-test" "--gtest_filter=TestVariant.swap")
add_test(TestVariant.iterator_array "kodi-test" "--gtest_filter=TestVariant.iterator_array")
add_test(TestVariant.iterator_map "kodi-test" "--gtest_filter=TestVariant.iterator_map")
add_test(TestVariant.size "kodi-test" "--gtest_filter=TestVariant.size")
add_test(TestVariant.empty "kodi-test" "--gtest_filter=TestVariant.empty")
add_test(TestVariant.clear "kodi-test" "--gtest_filter=TestVariant.clear")
add_test(TestVariant.erase "kodi-test" "--gtest_filter=TestVariant.erase")
add_test(TestVariant.isMember "kodi-test" "--gtest_filter=TestVariant.isMember")
add_test(TestUrlOptions.Clear "kodi-test" "--gtest_filter=TestUrlOptions.Clear")
add_test(TestUrlOptions.AddOption "kodi-test" "--gtest_filter=TestUrlOptions.AddOption")
add_test(TestUrlOptions.AddOptions "kodi-test" "--gtest_filter=TestUrlOptions.AddOptions")
add_test(TestUrlOptions.RemoveOption "kodi-test" "--gtest_filter=TestUrlOptions.RemoveOption")
add_test(TestUrlOptions.HasOption "kodi-test" "--gtest_filter=TestUrlOptions.HasOption")
add_test(TestUrlOptions.GetOptions "kodi-test" "--gtest_filter=TestUrlOptions.GetOptions")
add_test(TestUrlOptions.GetOptionsString "kodi-test" "--gtest_filter=TestUrlOptions.GetOptionsString")
add_test(TestURIUtils.PathHasParent "kodi-test" "--gtest_filter=TestURIUtils.PathHasParent")
add_test(TestURIUtils.GetDirectory "kodi-test" "--gtest_filter=TestURIUtils.GetDirectory")
add_test(TestURIUtils.GetExtension "kodi-test" "--gtest_filter=TestURIUtils.GetExtension")
add_test(TestURIUtils.HasExtension "kodi-test" "--gtest_filter=TestURIUtils.HasExtension")
add_test(TestURIUtils.GetFileName "kodi-test" "--gtest_filter=TestURIUtils.GetFileName")
add_test(TestURIUtils.RemoveExtension "kodi-test" "--gtest_filter=TestURIUtils.RemoveExtension")
add_test(TestURIUtils.ReplaceExtension "kodi-test" "--gtest_filter=TestURIUtils.ReplaceExtension")
add_test(TestURIUtils.Split "kodi-test" "--gtest_filter=TestURIUtils.Split")
add_test(TestURIUtils.SplitPath "kodi-test" "--gtest_filter=TestURIUtils.SplitPath")
add_test(TestURIUtils.SplitPathLocal "kodi-test" "--gtest_filter=TestURIUtils.SplitPathLocal")
add_test(TestURIUtils.GetCommonPath "kodi-test" "--gtest_filter=TestURIUtils.GetCommonPath")
add_test(TestURIUtils.GetParentPath "kodi-test" "--gtest_filter=TestURIUtils.GetParentPath")
add_test(TestURIUtils.SubstitutePath "kodi-test" "--gtest_filter=TestURIUtils.SubstitutePath")
add_test(TestURIUtils.IsAddonsPath "kodi-test" "--gtest_filter=TestURIUtils.IsAddonsPath")
add_test(TestURIUtils.IsSourcesPath "kodi-test" "--gtest_filter=TestURIUtils.IsSourcesPath")
add_test(TestURIUtils.IsCDDA "kodi-test" "--gtest_filter=TestURIUtils.IsCDDA")
add_test(TestURIUtils.IsDOSPath "kodi-test" "--gtest_filter=TestURIUtils.IsDOSPath")
add_test(TestURIUtils.IsDVD "kodi-test" "--gtest_filter=TestURIUtils.IsDVD")
add_test(TestURIUtils.IsFTP "kodi-test" "--gtest_filter=TestURIUtils.IsFTP")
add_test(TestURIUtils.IsHD "kodi-test" "--gtest_filter=TestURIUtils.IsHD")
add_test(TestURIUtils.IsInArchive "kodi-test" "--gtest_filter=TestURIUtils.IsInArchive")
add_test(TestURIUtils.IsInRAR "kodi-test" "--gtest_filter=TestURIUtils.IsInRAR")
add_test(TestURIUtils.IsInternetStream "kodi-test" "--gtest_filter=TestURIUtils.IsInternetStream")
add_test(TestURIUtils.IsInZIP "kodi-test" "--gtest_filter=TestURIUtils.IsInZIP")
add_test(TestURIUtils.IsISO9660 "kodi-test" "--gtest_filter=TestURIUtils.IsISO9660")
add_test(TestURIUtils.IsLiveTV "kodi-test" "--gtest_filter=TestURIUtils.IsLiveTV")
add_test(TestURIUtils.IsMultiPath "kodi-test" "--gtest_filter=TestURIUtils.IsMultiPath")
add_test(TestURIUtils.IsMusicDb "kodi-test" "--gtest_filter=TestURIUtils.IsMusicDb")
add_test(TestURIUtils.IsNfs "kodi-test" "--gtest_filter=TestURIUtils.IsNfs")
add_test(TestURIUtils.IsOnDVD "kodi-test" "--gtest_filter=TestURIUtils.IsOnDVD")
add_test(TestURIUtils.IsOnLAN "kodi-test" "--gtest_filter=TestURIUtils.IsOnLAN")
add_test(TestURIUtils.IsPlugin "kodi-test" "--gtest_filter=TestURIUtils.IsPlugin")
add_test(TestURIUtils.IsScript "kodi-test" "--gtest_filter=TestURIUtils.IsScript")
add_test(TestURIUtils.IsRAR "kodi-test" "--gtest_filter=TestURIUtils.IsRAR")
add_test(TestURIUtils.IsRemote "kodi-test" "--gtest_filter=TestURIUtils.IsRemote")
add_test(TestURIUtils.IsSmb "kodi-test" "--gtest_filter=TestURIUtils.IsSmb")
add_test(TestURIUtils.IsSpecial "kodi-test" "--gtest_filter=TestURIUtils.IsSpecial")
add_test(TestURIUtils.IsStack "kodi-test" "--gtest_filter=TestURIUtils.IsStack")
add_test(TestURIUtils.IsUPnP "kodi-test" "--gtest_filter=TestURIUtils.IsUPnP")
add_test(TestURIUtils.IsURL "kodi-test" "--gtest_filter=TestURIUtils.IsURL")
add_test(TestURIUtils.IsVideoDb "kodi-test" "--gtest_filter=TestURIUtils.IsVideoDb")
add_test(TestURIUtils.IsZIP "kodi-test" "--gtest_filter=TestURIUtils.IsZIP")
add_test(TestURIUtils.IsBluray "kodi-test" "--gtest_filter=TestURIUtils.IsBluray")
add_test(TestURIUtils.AddSlashAtEnd "kodi-test" "--gtest_filter=TestURIUtils.AddSlashAtEnd")
add_test(TestURIUtils.HasSlashAtEnd "kodi-test" "--gtest_filter=TestURIUtils.HasSlashAtEnd")
add_test(TestURIUtils.RemoveSlashAtEnd "kodi-test" "--gtest_filter=TestURIUtils.RemoveSlashAtEnd")
add_test(TestURIUtils.CreateArchivePath "kodi-test" "--gtest_filter=TestURIUtils.CreateArchivePath")
add_test(TestURIUtils.AddFileToFolder "kodi-test" "--gtest_filter=TestURIUtils.AddFileToFolder")
add_test(TestURIUtils.HasParentInHostname "kodi-test" "--gtest_filter=TestURIUtils.HasParentInHostname")
add_test(TestURIUtils.HasEncodedHostname "kodi-test" "--gtest_filter=TestURIUtils.HasEncodedHostname")
add_test(TestURIUtils.HasEncodedFilename "kodi-test" "--gtest_filter=TestURIUtils.HasEncodedFilename")
add_test(TestURIUtils.GetRealPath "kodi-test" "--gtest_filter=TestURIUtils.GetRealPath")
add_test(TestURIUtils.UpdateUrlEncoding "kodi-test" "--gtest_filter=TestURIUtils.UpdateUrlEncoding")
add_test(TestSystemInfo.Print_System_Info "kodi-test" "--gtest_filter=TestSystemInfo.Print_System_Info")
add_test(TestSystemInfo.GetKernelName "kodi-test" "--gtest_filter=TestSystemInfo.GetKernelName")
add_test(TestSystemInfo.GetKernelVersionFull "kodi-test" "--gtest_filter=TestSystemInfo.GetKernelVersionFull")
add_test(TestSystemInfo.GetKernelVersion "kodi-test" "--gtest_filter=TestSystemInfo.GetKernelVersion")
add_test(TestSystemInfo.GetOsName "kodi-test" "--gtest_filter=TestSystemInfo.GetOsName")
add_test(TestSystemInfo.DISABLED_GetOsVersion "kodi-test" "--gtest_filter=TestSystemInfo.DISABLED_GetOsVersion")
add_test(TestSystemInfo.GetOsPrettyNameWithVersion "kodi-test" "--gtest_filter=TestSystemInfo.GetOsPrettyNameWithVersion")
add_test(TestSystemInfo.GetManufacturerName "kodi-test" "--gtest_filter=TestSystemInfo.GetManufacturerName")
add_test(TestSystemInfo.GetModelName "kodi-test" "--gtest_filter=TestSystemInfo.GetModelName")
add_test(TestSystemInfo.IsAeroDisabled "kodi-test" "--gtest_filter=TestSystemInfo.IsAeroDisabled")
add_test(TestSystemInfo.IsWindowsVersion "kodi-test" "--gtest_filter=TestSystemInfo.IsWindowsVersion")
add_test(TestSystemInfo.IsWindowsVersionAtLeast "kodi-test" "--gtest_filter=TestSystemInfo.IsWindowsVersionAtLeast")
add_test(TestSystemInfo.GetWindowsVersion "kodi-test" "--gtest_filter=TestSystemInfo.GetWindowsVersion")
add_test(TestSystemInfo.GetKernelBitness "kodi-test" "--gtest_filter=TestSystemInfo.GetKernelBitness")
add_test(TestSystemInfo.GetKernelCpuFamily "kodi-test" "--gtest_filter=TestSystemInfo.GetKernelCpuFamily")
add_test(TestSystemInfo.GetXbmcBitness "kodi-test" "--gtest_filter=TestSystemInfo.GetXbmcBitness")
add_test(TestSystemInfo.GetUserAgent "kodi-test" "--gtest_filter=TestSystemInfo.GetUserAgent")
add_test(TestSystemInfo.HasVideoToolBoxDecoder "kodi-test" "--gtest_filter=TestSystemInfo.HasVideoToolBoxDecoder")
add_test(TestSystemInfo.GetBuildTargetPlatformName "kodi-test" "--gtest_filter=TestSystemInfo.GetBuildTargetPlatformName")
add_test(TestSystemInfo.GetBuildTargetPlatformVersion "kodi-test" "--gtest_filter=TestSystemInfo.GetBuildTargetPlatformVersion")
add_test(TestSystemInfo.GetBuildTargetPlatformVersionDecoded "kodi-test" "--gtest_filter=TestSystemInfo.GetBuildTargetPlatformVersionDecoded")
add_test(TestSystemInfo.GetBuildTargetCpuFamily "kodi-test" "--gtest_filter=TestSystemInfo.GetBuildTargetCpuFamily")
add_test(TestSystemInfo.GetUsedCompilerNameAndVer "kodi-test" "--gtest_filter=TestSystemInfo.GetUsedCompilerNameAndVer")
add_test(TestSystemInfo.GetDiskSpace "kodi-test" "--gtest_filter=TestSystemInfo.GetDiskSpace")
add_test(TestStringUtils.Format "kodi-test" "--gtest_filter=TestStringUtils.Format")
add_test(TestStringUtils.ToUpper "kodi-test" "--gtest_filter=TestStringUtils.ToUpper")
add_test(TestStringUtils.ToLower "kodi-test" "--gtest_filter=TestStringUtils.ToLower")
add_test(TestStringUtils.ToCapitalize "kodi-test" "--gtest_filter=TestStringUtils.ToCapitalize")
add_test(TestStringUtils.EqualsNoCase "kodi-test" "--gtest_filter=TestStringUtils.EqualsNoCase")
add_test(TestStringUtils.Left "kodi-test" "--gtest_filter=TestStringUtils.Left")
add_test(TestStringUtils.Mid "kodi-test" "--gtest_filter=TestStringUtils.Mid")
add_test(TestStringUtils.Right "kodi-test" "--gtest_filter=TestStringUtils.Right")
add_test(TestStringUtils.Trim "kodi-test" "--gtest_filter=TestStringUtils.Trim")
add_test(TestStringUtils.TrimLeft "kodi-test" "--gtest_filter=TestStringUtils.TrimLeft")
add_test(TestStringUtils.TrimRight "kodi-test" "--gtest_filter=TestStringUtils.TrimRight")
add_test(TestStringUtils.Replace "kodi-test" "--gtest_filter=TestStringUtils.Replace")
add_test(TestStringUtils.StartsWith "kodi-test" "--gtest_filter=TestStringUtils.StartsWith")
add_test(TestStringUtils.EndsWith "kodi-test" "--gtest_filter=TestStringUtils.EndsWith")
add_test(TestStringUtils.Join "kodi-test" "--gtest_filter=TestStringUtils.Join")
add_test(TestStringUtils.Split "kodi-test" "--gtest_filter=TestStringUtils.Split")
add_test(TestStringUtils.FindNumber "kodi-test" "--gtest_filter=TestStringUtils.FindNumber")
add_test(TestStringUtils.AlphaNumericCompare "kodi-test" "--gtest_filter=TestStringUtils.AlphaNumericCompare")
add_test(TestStringUtils.TimeStringToSeconds "kodi-test" "--gtest_filter=TestStringUtils.TimeStringToSeconds")
add_test(TestStringUtils.RemoveCRLF "kodi-test" "--gtest_filter=TestStringUtils.RemoveCRLF")
add_test(TestStringUtils.utf8_strlen "kodi-test" "--gtest_filter=TestStringUtils.utf8_strlen")
add_test(TestStringUtils.SecondsToTimeString "kodi-test" "--gtest_filter=TestStringUtils.SecondsToTimeString")
add_test(TestStringUtils.IsNaturalNumber "kodi-test" "--gtest_filter=TestStringUtils.IsNaturalNumber")
add_test(TestStringUtils.IsInteger "kodi-test" "--gtest_filter=TestStringUtils.IsInteger")
add_test(TestStringUtils.SizeToString "kodi-test" "--gtest_filter=TestStringUtils.SizeToString")
add_test(TestStringUtils.EmptyString "kodi-test" "--gtest_filter=TestStringUtils.EmptyString")
add_test(TestStringUtils.FindWords "kodi-test" "--gtest_filter=TestStringUtils.FindWords")
add_test(TestStringUtils.FindWords_NonAscii "kodi-test" "--gtest_filter=TestStringUtils.FindWords_NonAscii")
add_test(TestStringUtils.FindEndBracket "kodi-test" "--gtest_filter=TestStringUtils.FindEndBracket")
add_test(TestStringUtils.DateStringToYYYYMMDD "kodi-test" "--gtest_filter=TestStringUtils.DateStringToYYYYMMDD")
add_test(TestStringUtils.WordToDigits "kodi-test" "--gtest_filter=TestStringUtils.WordToDigits")
add_test(TestStringUtils.CreateUUID "kodi-test" "--gtest_filter=TestStringUtils.CreateUUID")
add_test(TestStringUtils.ValidateUUID "kodi-test" "--gtest_filter=TestStringUtils.ValidateUUID")
add_test(TestStringUtils.CompareFuzzy "kodi-test" "--gtest_filter=TestStringUtils.CompareFuzzy")
add_test(TestStringUtils.FindBestMatch "kodi-test" "--gtest_filter=TestStringUtils.FindBestMatch")
add_test(TestStringUtils.Paramify "kodi-test" "--gtest_filter=TestStringUtils.Paramify")
add_test(TestStringUtils.sortstringbyname "kodi-test" "--gtest_filter=TestStringUtils.sortstringbyname")
add_test(TestStringUtils.FileSizeFormat "kodi-test" "--gtest_filter=TestStringUtils.FileSizeFormat")
add_test(TestStringUtils.ToHexadecimal "kodi-test" "--gtest_filter=TestStringUtils.ToHexadecimal")
add_test(TestStreamUtils.General "kodi-test" "--gtest_filter=TestStreamUtils.General")
add_test(TestStreamDetails.General "kodi-test" "--gtest_filter=TestStreamDetails.General")
add_test(TestStreamDetails.VideoDimsToResolutionDescription "kodi-test" "--gtest_filter=TestStreamDetails.VideoDimsToResolutionDescription")
add_test(TestStreamDetails.VideoAspectToAspectDescription "kodi-test" "--gtest_filter=TestStreamDetails.VideoAspectToAspectDescription")
add_test(TestStopWatch.Initialization "kodi-test" "--gtest_filter=TestStopWatch.Initialization")
add_test(TestStopWatch.Start "kodi-test" "--gtest_filter=TestStopWatch.Start")
add_test(TestStopWatch.Stop "kodi-test" "--gtest_filter=TestStopWatch.Stop")
add_test(TestStopWatch.ElapsedTime "kodi-test" "--gtest_filter=TestStopWatch.ElapsedTime")
add_test(TestStopWatch.Reset "kodi-test" "--gtest_filter=TestStopWatch.Reset")
add_test(TestSortUtils.Sort_SortBy "kodi-test" "--gtest_filter=TestSortUtils.Sort_SortBy")
add_test(TestSortUtils.Sort_SortDescription "kodi-test" "--gtest_filter=TestSortUtils.Sort_SortDescription")
add_test(TestSortUtils.GetFieldsForSorting "kodi-test" "--gtest_filter=TestSortUtils.GetFieldsForSorting")
add_test(TestScraperUrl.General "kodi-test" "--gtest_filter=TestScraperUrl.General")
add_test(TestScraperParser.General "kodi-test" "--gtest_filter=TestScraperParser.General")
add_test(TestRingBuffer.General "kodi-test" "--gtest_filter=TestRingBuffer.General")
add_test(TestRFFT.SimpleSignal "kodi-test" "--gtest_filter=TestRFFT.SimpleSignal")
add_test(TestRegExp.RegFind "kodi-test" "--gtest_filter=TestRegExp.RegFind")
add_test(TestRegExp.GetReplaceString "kodi-test" "--gtest_filter=TestRegExp.GetReplaceString")
add_test(TestRegExp.GetFindLen "kodi-test" "--gtest_filter=TestRegExp.GetFindLen")
add_test(TestRegExp.GetSubCount "kodi-test" "--gtest_filter=TestRegExp.GetSubCount")
add_test(TestRegExp.GetSubStart "kodi-test" "--gtest_filter=TestRegExp.GetSubStart")
add_test(TestRegExp.GetCaptureTotal "kodi-test" "--gtest_filter=TestRegExp.GetCaptureTotal")
add_test(TestRegExp.GetMatch "kodi-test" "--gtest_filter=TestRegExp.GetMatch")
add_test(TestRegExp.GetPattern "kodi-test" "--gtest_filter=TestRegExp.GetPattern")
add_test(TestRegExp.GetNamedSubPattern "kodi-test" "--gtest_filter=TestRegExp.GetNamedSubPattern")
add_test(TestRegExp.operatorEqual "kodi-test" "--gtest_filter=TestRegExp.operatorEqual")
add_test(TestRegExpLog.DumpOvector "kodi-test" "--gtest_filter=TestRegExpLog.DumpOvector")
add_test(TestPOUtils.General "kodi-test" "--gtest_filter=TestPOUtils.General")
add_test(TestMime.GetMimeType_string "kodi-test" "--gtest_filter=TestMime.GetMimeType_string")
add_test(TestMime.GetMimeType_CFileItem "kodi-test" "--gtest_filter=TestMime.GetMimeType_CFileItem")
add_test(TestMathUtils.round_int "kodi-test" "--gtest_filter=TestMathUtils.round_int")
add_test(TestMathUtils.truncate_int "kodi-test" "--gtest_filter=TestMathUtils.truncate_int")
add_test(TestMathUtils.abs "kodi-test" "--gtest_filter=TestMathUtils.abs")
add_test(TestMathUtils.bitcount "kodi-test" "--gtest_filter=TestMathUtils.bitcount")
add_test(Testlog.Log "kodi-test" "--gtest_filter=Testlog.Log")
add_test(Testlog.MemDump "kodi-test" "--gtest_filter=Testlog.MemDump")
add_test(Testlog.SetLogLevel "kodi-test" "--gtest_filter=Testlog.SetLogLevel")
add_test(TestLocale.DefaultLocale "kodi-test" "--gtest_filter=TestLocale.DefaultLocale")
add_test(TestLocale.LanguageLocale "kodi-test" "--gtest_filter=TestLocale.LanguageLocale")
add_test(TestLocale.LanguageTerritoryLocale "kodi-test" "--gtest_filter=TestLocale.LanguageTerritoryLocale")
add_test(TestLocale.LanguageCodesetLocale "kodi-test" "--gtest_filter=TestLocale.LanguageCodesetLocale")
add_test(TestLocale.LanguageModifierLocale "kodi-test" "--gtest_filter=TestLocale.LanguageModifierLocale")
add_test(TestLocale.LanguageTerritoryCodesetLocale "kodi-test" "--gtest_filter=TestLocale.LanguageTerritoryCodesetLocale")
add_test(TestLocale.LanguageTerritoryModifierLocale "kodi-test" "--gtest_filter=TestLocale.LanguageTerritoryModifierLocale")
add_test(TestLocale.LanguageTerritoryCodesetModifierLocale "kodi-test" "--gtest_filter=TestLocale.LanguageTerritoryCodesetModifierLocale")
add_test(TestLocale.FullStringLocale "kodi-test" "--gtest_filter=TestLocale.FullStringLocale")
add_test(TestLocale.FromString "kodi-test" "--gtest_filter=TestLocale.FromString")
add_test(TestLocale.EmptyLocale "kodi-test" "--gtest_filter=TestLocale.EmptyLocale")
add_test(TestLocale.Equals "kodi-test" "--gtest_filter=TestLocale.Equals")
add_test(TestLangCodeExpander.ConvertISO6391ToISO6392B "kodi-test" "--gtest_filter=TestLangCodeExpander.ConvertISO6391ToISO6392B")
add_test(TestLangCodeExpander.ConvertToISO6392B "kodi-test" "--gtest_filter=TestLangCodeExpander.ConvertToISO6392B")
add_test(TestLabelFormatter.FormatLabel "kodi-test" "--gtest_filter=TestLabelFormatter.FormatLabel")
add_test(TestLabelFormatter.FormatLabel2 "kodi-test" "--gtest_filter=TestLabelFormatter.FormatLabel2")
add_test(TestJSONVariantWriter.CanWriteNull "kodi-test" "--gtest_filter=TestJSONVariantWriter.CanWriteNull")
add_test(TestJSONVariantWriter.CanWriteBoolean "kodi-test" "--gtest_filter=TestJSONVariantWriter.CanWriteBoolean")
add_test(TestJSONVariantWriter.CanWriteSignedInteger "kodi-test" "--gtest_filter=TestJSONVariantWriter.CanWriteSignedInteger")
add_test(TestJSONVariantWriter.CanWriteUnsignedInteger "kodi-test" "--gtest_filter=TestJSONVariantWriter.CanWriteUnsignedInteger")
add_test(TestJSONVariantWriter.CanWriteSignedInteger64 "kodi-test" "--gtest_filter=TestJSONVariantWriter.CanWriteSignedInteger64")
add_test(TestJSONVariantWriter.CanWriteUnsignedInteger64 "kodi-test" "--gtest_filter=TestJSONVariantWriter.CanWriteUnsignedInteger64")
add_test(TestJSONVariantWriter.CanWriteDouble "kodi-test" "--gtest_filter=TestJSONVariantWriter.CanWriteDouble")
add_test(TestJSONVariantWriter.CanWriteString "kodi-test" "--gtest_filter=TestJSONVariantWriter.CanWriteString")
add_test(TestJSONVariantWriter.CanWriteObject "kodi-test" "--gtest_filter=TestJSONVariantWriter.CanWriteObject")
add_test(TestJSONVariantWriter.CanWriteArray "kodi-test" "--gtest_filter=TestJSONVariantWriter.CanWriteArray")
add_test(TestJSONVariantParser.CannotParseNullptr "kodi-test" "--gtest_filter=TestJSONVariantParser.CannotParseNullptr")
add_test(TestJSONVariantParser.CannotParseEmptyString "kodi-test" "--gtest_filter=TestJSONVariantParser.CannotParseEmptyString")
add_test(TestJSONVariantParser.CannotParseInvalidJson "kodi-test" "--gtest_filter=TestJSONVariantParser.CannotParseInvalidJson")
add_test(TestJSONVariantParser.CanParseNull "kodi-test" "--gtest_filter=TestJSONVariantParser.CanParseNull")
add_test(TestJSONVariantParser.CanParseBoolean "kodi-test" "--gtest_filter=TestJSONVariantParser.CanParseBoolean")
add_test(TestJSONVariantParser.CanParseSignedInteger "kodi-test" "--gtest_filter=TestJSONVariantParser.CanParseSignedInteger")
add_test(TestJSONVariantParser.CanParseUnsignedInteger "kodi-test" "--gtest_filter=TestJSONVariantParser.CanParseUnsignedInteger")
add_test(TestJSONVariantParser.CanParseSignedInteger64 "kodi-test" "--gtest_filter=TestJSONVariantParser.CanParseSignedInteger64")
add_test(TestJSONVariantParser.CanParseUnsignedInteger64 "kodi-test" "--gtest_filter=TestJSONVariantParser.CanParseUnsignedInteger64")
add_test(TestJSONVariantParser.CanParseDouble "kodi-test" "--gtest_filter=TestJSONVariantParser.CanParseDouble")
add_test(TestJSONVariantParser.CanParseString "kodi-test" "--gtest_filter=TestJSONVariantParser.CanParseString")
add_test(TestJSONVariantParser.CanParseObject "kodi-test" "--gtest_filter=TestJSONVariantParser.CanParseObject")
add_test(TestJSONVariantParser.CanParseArray "kodi-test" "--gtest_filter=TestJSONVariantParser.CanParseArray")
add_test(TestJobManager.AddJob "kodi-test" "--gtest_filter=TestJobManager.AddJob")
add_test(TestJobManager.CancelJob "kodi-test" "--gtest_filter=TestJobManager.CancelJob")
add_test(TestJobManager.PauseLowPriorityJob "kodi-test" "--gtest_filter=TestJobManager.PauseLowPriorityJob")
add_test(TestJobManager.IsProcessing "kodi-test" "--gtest_filter=TestJobManager.IsProcessing")
add_test(TestHttpResponse.General "kodi-test" "--gtest_filter=TestHttpResponse.General")
add_test(TestHttpRange.FirstPosition "kodi-test" "--gtest_filter=TestHttpRange.FirstPosition")
add_test(TestHttpRange.LastPosition "kodi-test" "--gtest_filter=TestHttpRange.LastPosition")
add_test(TestHttpRange.Length "kodi-test" "--gtest_filter=TestHttpRange.Length")
add_test(TestHttpRange.IsValid "kodi-test" "--gtest_filter=TestHttpRange.IsValid")
add_test(TestHttpRange.Ctor "kodi-test" "--gtest_filter=TestHttpRange.Ctor")
add_test(TestHttpResponseRange.SetData "kodi-test" "--gtest_filter=TestHttpResponseRange.SetData")
add_test(TestHttpRanges.Ctor "kodi-test" "--gtest_filter=TestHttpRanges.Ctor")
add_test(TestHttpRanges.GetAll "kodi-test" "--gtest_filter=TestHttpRanges.GetAll")
add_test(TestHttpRanges.GetIndex "kodi-test" "--gtest_filter=TestHttpRanges.GetIndex")
add_test(TestHttpRanges.GetFirst "kodi-test" "--gtest_filter=TestHttpRanges.GetFirst")
add_test(TestHttpRanges.GetLast "kodi-test" "--gtest_filter=TestHttpRanges.GetLast")
add_test(TestHttpRanges.Size "kodi-test" "--gtest_filter=TestHttpRanges.Size")
add_test(TestHttpRanges.GetFirstPosition "kodi-test" "--gtest_filter=TestHttpRanges.GetFirstPosition")
add_test(TestHttpRanges.GetLastPosition "kodi-test" "--gtest_filter=TestHttpRanges.GetLastPosition")
add_test(TestHttpRanges.GetLength "kodi-test" "--gtest_filter=TestHttpRanges.GetLength")
add_test(TestHttpRanges.GetTotalRange "kodi-test" "--gtest_filter=TestHttpRanges.GetTotalRange")
add_test(TestHttpRanges.Add "kodi-test" "--gtest_filter=TestHttpRanges.Add")
add_test(TestHttpRanges.Remove "kodi-test" "--gtest_filter=TestHttpRanges.Remove")
add_test(TestHttpRanges.Clear "kodi-test" "--gtest_filter=TestHttpRanges.Clear")
add_test(TestHttpRanges.ParseInvalid "kodi-test" "--gtest_filter=TestHttpRanges.ParseInvalid")
add_test(TestHttpRanges.ParseStartOnly "kodi-test" "--gtest_filter=TestHttpRanges.ParseStartOnly")
add_test(TestHttpRanges.ParseFromEnd "kodi-test" "--gtest_filter=TestHttpRanges.ParseFromEnd")
add_test(TestHttpRanges.ParseSingle "kodi-test" "--gtest_filter=TestHttpRanges.ParseSingle")
add_test(TestHttpRanges.ParseMulti "kodi-test" "--gtest_filter=TestHttpRanges.ParseMulti")
add_test(TestHttpRanges.ParseOrderedNotOverlapping "kodi-test" "--gtest_filter=TestHttpRanges.ParseOrderedNotOverlapping")
add_test(TestHttpRanges.ParseOrderedBackToBack "kodi-test" "--gtest_filter=TestHttpRanges.ParseOrderedBackToBack")
add_test(TestHttpRanges.ParseOrderedOverlapping "kodi-test" "--gtest_filter=TestHttpRanges.ParseOrderedOverlapping")
add_test(TestHttpRanges.ParseUnorderedNotOverlapping "kodi-test" "--gtest_filter=TestHttpRanges.ParseUnorderedNotOverlapping")
add_test(TestHttpRanges.ParseUnorderedBackToBack "kodi-test" "--gtest_filter=TestHttpRanges.ParseUnorderedBackToBack")
add_test(TestHttpRanges.ParseUnorderedOverlapping "kodi-test" "--gtest_filter=TestHttpRanges.ParseUnorderedOverlapping")
add_test(TestHttpParser.General "kodi-test" "--gtest_filter=TestHttpParser.General")
add_test(TestHttpHeader.General "kodi-test" "--gtest_filter=TestHttpHeader.General")
add_test(TestHttpHeader.Parse "kodi-test" "--gtest_filter=TestHttpHeader.Parse")
add_test(TestHttpHeader.Parse_Multiline "kodi-test" "--gtest_filter=TestHttpHeader.Parse_Multiline")
add_test(TestHttpHeader.GetValue "kodi-test" "--gtest_filter=TestHttpHeader.GetValue")
add_test(TestHttpHeader.GetValues "kodi-test" "--gtest_filter=TestHttpHeader.GetValues")
add_test(TestHttpHeader.AddParam "kodi-test" "--gtest_filter=TestHttpHeader.AddParam")
add_test(TestHttpHeader.GetMimeType "kodi-test" "--gtest_filter=TestHttpHeader.GetMimeType")
add_test(TestHttpHeader.GetCharset "kodi-test" "--gtest_filter=TestHttpHeader.GetCharset")
add_test(TestHTMLUtil.RemoveTags "kodi-test" "--gtest_filter=TestHTMLUtil.RemoveTags")
add_test(TestHTMLUtil.ConvertHTMLToW "kodi-test" "--gtest_filter=TestHTMLUtil.ConvertHTMLToW")
add_test(TestGlobal.Pattern1 "kodi-test" "--gtest_filter=TestGlobal.Pattern1")
add_test(TestFileUtils.DeleteItem_CFileItemPtr "kodi-test" "--gtest_filter=TestFileUtils.DeleteItem_CFileItemPtr")
add_test(TestFileUtils.DeleteItemString "kodi-test" "--gtest_filter=TestFileUtils.DeleteItemString")
add_test(TestFileOperationJob.ActionCopy "kodi-test" "--gtest_filter=TestFileOperationJob.ActionCopy")
add_test(TestFileOperationJob.ActionMove "kodi-test" "--gtest_filter=TestFileOperationJob.ActionMove")
add_test(TestFileOperationJob.ActionDelete "kodi-test" "--gtest_filter=TestFileOperationJob.ActionDelete")
add_test(TestFileOperationJob.ActionReplace "kodi-test" "--gtest_filter=TestFileOperationJob.ActionReplace")
add_test(TestFileOperationJob.ActionCreateFolder "kodi-test" "--gtest_filter=TestFileOperationJob.ActionCreateFolder")
add_test(TestFileOperationJob.ActionDeleteFolder "kodi-test" "--gtest_filter=TestFileOperationJob.ActionDeleteFolder")
add_test(TestFileOperationJob.GetFunctions "kodi-test" "--gtest_filter=TestFileOperationJob.GetFunctions")
add_test(TestEndianSwap.Endian_Swap16 "kodi-test" "--gtest_filter=TestEndianSwap.Endian_Swap16")
add_test(TestEndianSwap.Endian_Swap32 "kodi-test" "--gtest_filter=TestEndianSwap.Endian_Swap32")
add_test(TestEndianSwap.Endian_Swap64 "kodi-test" "--gtest_filter=TestEndianSwap.Endian_Swap64")
add_test(TestEndianSwap.Endian_SwapLE16 "kodi-test" "--gtest_filter=TestEndianSwap.Endian_SwapLE16")
add_test(TestEndianSwap.Endian_SwapLE32 "kodi-test" "--gtest_filter=TestEndianSwap.Endian_SwapLE32")
add_test(TestEndianSwap.Endian_SwapLE64 "kodi-test" "--gtest_filter=TestEndianSwap.Endian_SwapLE64")
add_test(TestEndianSwap.Endian_SwapBE16 "kodi-test" "--gtest_filter=TestEndianSwap.Endian_SwapBE16")
add_test(TestEndianSwap.Endian_SwapBE32 "kodi-test" "--gtest_filter=TestEndianSwap.Endian_SwapBE32")
add_test(TestEndianSwap.Endian_SwapBE64 "kodi-test" "--gtest_filter=TestEndianSwap.Endian_SwapBE64")
add_test(TestDigest.Digest_Empty "kodi-test" "--gtest_filter=TestDigest.Digest_Empty")
add_test(TestDigest.Digest_Basic "kodi-test" "--gtest_filter=TestDigest.Digest_Basic")
add_test(TestDigest.Digest_SHA1 "kodi-test" "--gtest_filter=TestDigest.Digest_SHA1")
add_test(TestDigest.Digest_SHA256 "kodi-test" "--gtest_filter=TestDigest.Digest_SHA256")
add_test(TestDigest.Digest_SHA512 "kodi-test" "--gtest_filter=TestDigest.Digest_SHA512")
add_test(TestDigest.TypedDigest_Empty "kodi-test" "--gtest_filter=TestDigest.TypedDigest_Empty")
add_test(TestDigest.TypedDigest_SameType "kodi-test" "--gtest_filter=TestDigest.TypedDigest_SameType")
add_test(TestDigest.TypedDigest_CompareCase "kodi-test" "--gtest_filter=TestDigest.TypedDigest_CompareCase")
add_test(TestDigest.TypedDigest_DifferingType "kodi-test" "--gtest_filter=TestDigest.TypedDigest_DifferingType")
add_test(TestDatabaseUtils.GetField_None "kodi-test" "--gtest_filter=TestDatabaseUtils.GetField_None")
add_test(TestDatabaseUtils.GetField_MediaTypeAlbum "kodi-test" "--gtest_filter=TestDatabaseUtils.GetField_MediaTypeAlbum")
add_test(TestDatabaseUtils.GetField_MediaTypeSong "kodi-test" "--gtest_filter=TestDatabaseUtils.GetField_MediaTypeSong")
add_test(TestDatabaseUtils.GetField_MediaTypeMusicVideo "kodi-test" "--gtest_filter=TestDatabaseUtils.GetField_MediaTypeMusicVideo")
add_test(TestDatabaseUtils.GetField_MediaTypeMovie "kodi-test" "--gtest_filter=TestDatabaseUtils.GetField_MediaTypeMovie")
add_test(TestDatabaseUtils.GetField_MediaTypeTvShow "kodi-test" "--gtest_filter=TestDatabaseUtils.GetField_MediaTypeTvShow")
add_test(TestDatabaseUtils.GetField_MediaTypeEpisode "kodi-test" "--gtest_filter=TestDatabaseUtils.GetField_MediaTypeEpisode")
add_test(TestDatabaseUtils.GetField_FieldRandom "kodi-test" "--gtest_filter=TestDatabaseUtils.GetField_FieldRandom")
add_test(TestDatabaseUtils.GetFieldIndex_None "kodi-test" "--gtest_filter=TestDatabaseUtils.GetFieldIndex_None")
add_test(TestDatabaseUtils.GetFieldIndex_MediaTypeAlbum "kodi-test" "--gtest_filter=TestDatabaseUtils.GetFieldIndex_MediaTypeAlbum")
add_test(TestDatabaseUtils.GetFieldIndex_MediaTypeSong "kodi-test" "--gtest_filter=TestDatabaseUtils.GetFieldIndex_MediaTypeSong")
add_test(TestDatabaseUtils.GetFieldIndex_MediaTypeMusicVideo "kodi-test" "--gtest_filter=TestDatabaseUtils.GetFieldIndex_MediaTypeMusicVideo")
add_test(TestDatabaseUtils.GetFieldIndex_MediaTypeMovie "kodi-test" "--gtest_filter=TestDatabaseUtils.GetFieldIndex_MediaTypeMovie")
add_test(TestDatabaseUtils.GetFieldIndex_MediaTypeTvShow "kodi-test" "--gtest_filter=TestDatabaseUtils.GetFieldIndex_MediaTypeTvShow")
add_test(TestDatabaseUtils.GetFieldIndex_MediaTypeEpisode "kodi-test" "--gtest_filter=TestDatabaseUtils.GetFieldIndex_MediaTypeEpisode")
add_test(TestDatabaseUtils.GetSelectFields "kodi-test" "--gtest_filter=TestDatabaseUtils.GetSelectFields")
add_test(TestDatabaseUtils.GetFieldValue "kodi-test" "--gtest_filter=TestDatabaseUtils.GetFieldValue")
add_test(TestDatabaseUtils.GetDatabaseResults "kodi-test" "--gtest_filter=TestDatabaseUtils.GetDatabaseResults")
add_test(TestDatabaseUtils.BuildLimitClause "kodi-test" "--gtest_filter=TestDatabaseUtils.BuildLimitClause")
add_test(TestCrc32.Compute_1 "kodi-test" "--gtest_filter=TestCrc32.Compute_1")
add_test(TestCrc32.Compute_2 "kodi-test" "--gtest_filter=TestCrc32.Compute_2")
add_test(TestCrc32.ComputeFromLowerCase "kodi-test" "--gtest_filter=TestCrc32.ComputeFromLowerCase")
add_test(TestCrc32.Reset "kodi-test" "--gtest_filter=TestCrc32.Reset")
add_test(TestCPUInfo.getUsedPercentage "kodi-test" "--gtest_filter=TestCPUInfo.getUsedPercentage")
add_test(TestCPUInfo.getCPUCount "kodi-test" "--gtest_filter=TestCPUInfo.getCPUCount")
add_test(TestCPUInfo.getCPUFrequency "kodi-test" "--gtest_filter=TestCPUInfo.getCPUFrequency")
add_test(TestCPUInfo.getTemperature "kodi-test" "--gtest_filter=TestCPUInfo.getTemperature")
add_test(TestCPUInfo.getCPUModel "kodi-test" "--gtest_filter=TestCPUInfo.getCPUModel")
add_test(TestCPUInfo.getCPUBogoMips "kodi-test" "--gtest_filter=TestCPUInfo.getCPUBogoMips")
add_test(TestCPUInfo.getCPUHardware "kodi-test" "--gtest_filter=TestCPUInfo.getCPUHardware")
add_test(TestCPUInfo.getCPURevision "kodi-test" "--gtest_filter=TestCPUInfo.getCPURevision")
add_test(TestCPUInfo.getCPUSerial "kodi-test" "--gtest_filter=TestCPUInfo.getCPUSerial")
add_test(TestCPUInfo.CoreInfo "kodi-test" "--gtest_filter=TestCPUInfo.CoreInfo")
add_test(TestCPUInfo.GetCoresUsageString "kodi-test" "--gtest_filter=TestCPUInfo.GetCoresUsageString")
add_test(TestCPUInfo.GetCPUFeatures "kodi-test" "--gtest_filter=TestCPUInfo.GetCPUFeatures")
add_test(TestCPUInfo.getUsedPercentage_output "kodi-test" "--gtest_filter=TestCPUInfo.getUsedPercentage_output")
add_test(TestCharsetConverter.utf8ToW "kodi-test" "--gtest_filter=TestCharsetConverter.utf8ToW")
add_test(TestCharsetConverter.utf16LEtoW "kodi-test" "--gtest_filter=TestCharsetConverter.utf16LEtoW")
add_test(TestCharsetConverter.subtitleCharsetToUtf8 "kodi-test" "--gtest_filter=TestCharsetConverter.subtitleCharsetToUtf8")
add_test(TestCharsetConverter.utf8ToStringCharset_1 "kodi-test" "--gtest_filter=TestCharsetConverter.utf8ToStringCharset_1")
add_test(TestCharsetConverter.utf8ToStringCharset_2 "kodi-test" "--gtest_filter=TestCharsetConverter.utf8ToStringCharset_2")
add_test(TestCharsetConverter.utf8ToSystem "kodi-test" "--gtest_filter=TestCharsetConverter.utf8ToSystem")
add_test(TestCharsetConverter.utf8To_ASCII "kodi-test" "--gtest_filter=TestCharsetConverter.utf8To_ASCII")
add_test(TestCharsetConverter.utf8To_UTF16LE "kodi-test" "--gtest_filter=TestCharsetConverter.utf8To_UTF16LE")
add_test(TestCharsetConverter.utf8To_UTF32LE "kodi-test" "--gtest_filter=TestCharsetConverter.utf8To_UTF32LE")
add_test(TestCharsetConverter.stringCharsetToUtf8 "kodi-test" "--gtest_filter=TestCharsetConverter.stringCharsetToUtf8")
add_test(TestCharsetConverter.isValidUtf8_1 "kodi-test" "--gtest_filter=TestCharsetConverter.isValidUtf8_1")
add_test(TestCharsetConverter.isValidUtf8_2 "kodi-test" "--gtest_filter=TestCharsetConverter.isValidUtf8_2")
add_test(TestCharsetConverter.isValidUtf8_3 "kodi-test" "--gtest_filter=TestCharsetConverter.isValidUtf8_3")
add_test(TestCharsetConverter.isValidUtf8_4 "kodi-test" "--gtest_filter=TestCharsetConverter.isValidUtf8_4")
add_test(TestCharsetConverter.ucs2CharsetToStringCharset "kodi-test" "--gtest_filter=TestCharsetConverter.ucs2CharsetToStringCharset")
add_test(TestCharsetConverter.wToUTF8 "kodi-test" "--gtest_filter=TestCharsetConverter.wToUTF8")
add_test(TestCharsetConverter.utf16BEtoUTF8 "kodi-test" "--gtest_filter=TestCharsetConverter.utf16BEtoUTF8")
add_test(TestCharsetConverter.utf16LEtoUTF8 "kodi-test" "--gtest_filter=TestCharsetConverter.utf16LEtoUTF8")
add_test(TestCharsetConverter.ucs2ToUTF8 "kodi-test" "--gtest_filter=TestCharsetConverter.ucs2ToUTF8")
add_test(TestCharsetConverter.utf8logicalToVisualBiDi "kodi-test" "--gtest_filter=TestCharsetConverter.utf8logicalToVisualBiDi")
add_test(TestCharsetConverter.utf32ToStringCharset "kodi-test" "--gtest_filter=TestCharsetConverter.utf32ToStringCharset")
add_test(TestCharsetConverter.getCharsetLabels "kodi-test" "--gtest_filter=TestCharsetConverter.getCharsetLabels")
add_test(TestCharsetConverter.getCharsetLabelByName "kodi-test" "--gtest_filter=TestCharsetConverter.getCharsetLabelByName")
add_test(TestCharsetConverter.getCharsetNameByLabel "kodi-test" "--gtest_filter=TestCharsetConverter.getCharsetNameByLabel")
add_test(TestCharsetConverter.unknownToUTF8_1 "kodi-test" "--gtest_filter=TestCharsetConverter.unknownToUTF8_1")
add_test(TestCharsetConverter.unknownToUTF8_2 "kodi-test" "--gtest_filter=TestCharsetConverter.unknownToUTF8_2")
add_test(TestCharsetConverter.toW "kodi-test" "--gtest_filter=TestCharsetConverter.toW")
add_test(TestCharsetConverter.fromW "kodi-test" "--gtest_filter=TestCharsetConverter.fromW")
add_test(TestBitstreamStats.General "kodi-test" "--gtest_filter=TestBitstreamStats.General")
add_test(TestBase64.Encode_1 "kodi-test" "--gtest_filter=TestBase64.Encode_1")
add_test(TestBase64.Encode_2 "kodi-test" "--gtest_filter=TestBase64.Encode_2")
add_test(TestBase64.Encode_3 "kodi-test" "--gtest_filter=TestBase64.Encode_3")
add_test(TestBase64.Encode_4 "kodi-test" "--gtest_filter=TestBase64.Encode_4")
add_test(TestBase64.Decode_1 "kodi-test" "--gtest_filter=TestBase64.Decode_1")
add_test(TestBase64.Decode_2 "kodi-test" "--gtest_filter=TestBase64.Decode_2")
add_test(TestBase64.Decode_3 "kodi-test" "--gtest_filter=TestBase64.Decode_3")
add_test(TestBase64.Decode_4 "kodi-test" "--gtest_filter=TestBase64.Decode_4")
add_test(TestArchive.IsStoring "kodi-test" "--gtest_filter=TestArchive.IsStoring")
add_test(TestArchive.IsLoading "kodi-test" "--gtest_filter=TestArchive.IsLoading")
add_test(TestArchive.FloatArchive "kodi-test" "--gtest_filter=TestArchive.FloatArchive")
add_test(TestArchive.DoubleArchive "kodi-test" "--gtest_filter=TestArchive.DoubleArchive")
add_test(TestArchive.IntegerArchive "kodi-test" "--gtest_filter=TestArchive.IntegerArchive")
add_test(TestArchive.UnsignedIntegerArchive "kodi-test" "--gtest_filter=TestArchive.UnsignedIntegerArchive")
add_test(TestArchive.Int64tArchive "kodi-test" "--gtest_filter=TestArchive.Int64tArchive")
add_test(TestArchive.UInt64tArchive "kodi-test" "--gtest_filter=TestArchive.UInt64tArchive")
add_test(TestArchive.BoolArchive "kodi-test" "--gtest_filter=TestArchive.BoolArchive")
add_test(TestArchive.CharArchive "kodi-test" "--gtest_filter=TestArchive.CharArchive")
add_test(TestArchive.WStringArchive "kodi-test" "--gtest_filter=TestArchive.WStringArchive")
add_test(TestArchive.StringArchive "kodi-test" "--gtest_filter=TestArchive.StringArchive")
add_test(TestArchive.SYSTEMTIMEArchive "kodi-test" "--gtest_filter=TestArchive.SYSTEMTIMEArchive")
add_test(TestArchive.CVariantArchive "kodi-test" "--gtest_filter=TestArchive.CVariantArchive")
add_test(TestArchive.CVariantArchiveString "kodi-test" "--gtest_filter=TestArchive.CVariantArchiveString")
add_test(TestArchive.StringVectorArchive "kodi-test" "--gtest_filter=TestArchive.StringVectorArchive")
add_test(TestArchive.IntegerVectorArchive "kodi-test" "--gtest_filter=TestArchive.IntegerVectorArchive")
add_test(TestArchive.MultiTypeArchive "kodi-test" "--gtest_filter=TestArchive.MultiTypeArchive")
add_test(TestAliasShortcutUtils.IsAliasShortcut "kodi-test" "--gtest_filter=TestAliasShortcutUtils.IsAliasShortcut")
add_test(TestAliasShortcutUtils.TranslateAliasShortcut "kodi-test" "--gtest_filter=TestAliasShortcutUtils.TranslateAliasShortcut")
add_test(TestAlarmClock.General "kodi-test" "--gtest_filter=TestAlarmClock.General")
add_test(TestCritSection.General "kodi-test" "--gtest_filter=TestCritSection.General")
add_test(TestSharedSection.General "kodi-test" "--gtest_filter=TestSharedSection.General")
add_test(TestSharedSection.GetSharedLockWhileTryingExclusiveLock "kodi-test" "--gtest_filter=TestSharedSection.GetSharedLockWhileTryingExclusiveLock")
add_test(TestSharedSection.TwoCase "kodi-test" "--gtest_filter=TestSharedSection.TwoCase")
add_test(TestMultipleSharedSection.General "kodi-test" "--gtest_filter=TestMultipleSharedSection.General")
add_test(TestEvent.General "kodi-test" "--gtest_filter=TestEvent.General")
add_test(TestEvent.TwoWaits "kodi-test" "--gtest_filter=TestEvent.TwoWaits")
add_test(TestEvent.TimedWaits "kodi-test" "--gtest_filter=TestEvent.TimedWaits")
add_test(TestEvent.TimedWaitsTimeout "kodi-test" "--gtest_filter=TestEvent.TimedWaitsTimeout")
add_test(TestEvent.Group "kodi-test" "--gtest_filter=TestEvent.Group")
add_test(TestEvent.GroupLimitedGroupScope "kodi-test" "--gtest_filter=TestEvent.GroupLimitedGroupScope")
add_test(TestEvent.TwoGroups "kodi-test" "--gtest_filter=TestEvent.TwoGroups")
add_test(TestEvent.AutoResetBehavior "kodi-test" "--gtest_filter=TestEvent.AutoResetBehavior")
add_test(TestEvent.ManualReset "kodi-test" "--gtest_filter=TestEvent.ManualReset")
add_test(TestEvent.InitVal "kodi-test" "--gtest_filter=TestEvent.InitVal")
add_test(TestEvent.SimpleTimeout "kodi-test" "--gtest_filter=TestEvent.SimpleTimeout")
add_test(TestEvent.GroupChildSet "kodi-test" "--gtest_filter=TestEvent.GroupChildSet")
add_test(TestEvent.GroupChildSet2 "kodi-test" "--gtest_filter=TestEvent.GroupChildSet2")
add_test(TestEvent.GroupWaitResetsChild "kodi-test" "--gtest_filter=TestEvent.GroupWaitResetsChild")
add_test(TestEvent.GroupTimedWait "kodi-test" "--gtest_filter=TestEvent.GroupTimedWait")
add_test(TestMassEvent.General "kodi-test" "--gtest_filter=TestMassEvent.General")
add_test(TestMassEvent.Polling "kodi-test" "--gtest_filter=TestMassEvent.Polling")
add_test(TestPlayListXSPF.Load "kodi-test" "--gtest_filter=TestPlayListXSPF.Load")
add_test(TestPlayListFactory.XSPF "kodi-test" "--gtest_filter=TestPlayListFactory.XSPF")
add_test(TestWebServer.IsStarted "kodi-test" "--gtest_filter=TestWebServer.IsStarted")
add_test(TestWebServer.CanGetJsonRpcApiDescriptionWithHttpGet "kodi-test" "--gtest_filter=TestWebServer.CanGetJsonRpcApiDescriptionWithHttpGet")
add_test(TestWebServer.CanReadDataOverJsonRpcWithHttpGet "kodi-test" "--gtest_filter=TestWebServer.CanReadDataOverJsonRpcWithHttpGet")
add_test(TestWebServer.CannotModifyOverJsonRpcWithHttpGet "kodi-test" "--gtest_filter=TestWebServer.CannotModifyOverJsonRpcWithHttpGet")
add_test(TestWebServer.CanReadDataOverJsonRpcWithHttpPost "kodi-test" "--gtest_filter=TestWebServer.CanReadDataOverJsonRpcWithHttpPost")
add_test(TestWebServer.CanModifyOverJsonRpcWithHttpPost "kodi-test" "--gtest_filter=TestWebServer.CanModifyOverJsonRpcWithHttpPost")
add_test(TestWebServer.CanNotHeadNonExistingFile "kodi-test" "--gtest_filter=TestWebServer.CanNotHeadNonExistingFile")
add_test(TestWebServer.CanHeadFile "kodi-test" "--gtest_filter=TestWebServer.CanHeadFile")
add_test(TestWebServer.CanNotGetNonExistingFile "kodi-test" "--gtest_filter=TestWebServer.CanNotGetNonExistingFile")
add_test(TestWebServer.CanGetFile "kodi-test" "--gtest_filter=TestWebServer.CanGetFile")
add_test(TestWebServer.CanGetFileForcingNoCache "kodi-test" "--gtest_filter=TestWebServer.CanGetFileForcingNoCache")
add_test(TestWebServer.CanGetCachedFileWithOlderIfModifiedSince "kodi-test" "--gtest_filter=TestWebServer.CanGetCachedFileWithOlderIfModifiedSince")
add_test(TestWebServer.CanGetCachedFileWithExactIfModifiedSince "kodi-test" "--gtest_filter=TestWebServer.CanGetCachedFileWithExactIfModifiedSince")
add_test(TestWebServer.CanGetCachedFileWithNewerIfModifiedSince "kodi-test" "--gtest_filter=TestWebServer.CanGetCachedFileWithNewerIfModifiedSince")
add_test(TestWebServer.CanGetCachedFileWithNewerIfModifiedSinceForcingNoCache "kodi-test" "--gtest_filter=TestWebServer.CanGetCachedFileWithNewerIfModifiedSinceForcingNoCache")
add_test(TestWebServer.CanGetCachedFileWithOlderIfUnmodifiedSince "kodi-test" "--gtest_filter=TestWebServer.CanGetCachedFileWithOlderIfUnmodifiedSince")
add_test(TestWebServer.CanGetCachedFileWithExactIfUnmodifiedSince "kodi-test" "--gtest_filter=TestWebServer.CanGetCachedFileWithExactIfUnmodifiedSince")
add_test(TestWebServer.CanGetCachedFileWithNewerIfUnmodifiedSince "kodi-test" "--gtest_filter=TestWebServer.CanGetCachedFileWithNewerIfUnmodifiedSince")
add_test(TestWebServer.CanGetRangedFileRange0_ "kodi-test" "--gtest_filter=TestWebServer.CanGetRangedFileRange0_")
add_test(TestWebServer.CanGetRangedFileRange0_End "kodi-test" "--gtest_filter=TestWebServer.CanGetRangedFileRange0_End")
add_test(TestWebServer.CanGetRangedFileRange0_2xEnd "kodi-test" "--gtest_filter=TestWebServer.CanGetRangedFileRange0_2xEnd")
add_test(TestWebServer.CanGetRangedFileRange0_First "kodi-test" "--gtest_filter=TestWebServer.CanGetRangedFileRange0_First")
add_test(TestWebServer.CanGetRangedFileRangeFirst_Second "kodi-test" "--gtest_filter=TestWebServer.CanGetRangedFileRangeFirst_Second")
add_test(TestWebServer.CanGetRangedFileRange_Last "kodi-test" "--gtest_filter=TestWebServer.CanGetRangedFileRange_Last")
add_test(TestWebServer.CanGetRangedFileRangeFirstSecond "kodi-test" "--gtest_filter=TestWebServer.CanGetRangedFileRangeFirstSecond")
add_test(TestWebServer.CanGetRangedFileRangeFirstSecondLast "kodi-test" "--gtest_filter=TestWebServer.CanGetRangedFileRangeFirstSecondLast")
add_test(TestWebServer.CanGetCachedRangedFileWithOlderIfRange "kodi-test" "--gtest_filter=TestWebServer.CanGetCachedRangedFileWithOlderIfRange")
add_test(TestWebServer.CanGetCachedRangedFileWithExactIfRange "kodi-test" "--gtest_filter=TestWebServer.CanGetCachedRangedFileWithExactIfRange")
add_test(TestWebServer.CanGetCachedRangedFileWithNewerIfRange "kodi-test" "--gtest_filter=TestWebServer.CanGetCachedRangedFileWithNewerIfRange")
add_test(TestTagParser.ParsesBasicTag "kodi-test" "--gtest_filter=TestTagParser.ParsesBasicTag")
add_test(TestTagParser.HandleNullTag "kodi-test" "--gtest_filter=TestTagParser.HandleNullTag")
add_test(EmptyTagParser.EmptyProperties "kodi-test" "--gtest_filter=EmptyTagParser.EmptyProperties")
add_test(TestTagParser.FooProperties "kodi-test" "--gtest_filter=TestTagParser.FooProperties")
add_test(TestTagLoaderTagLib.SetGenre "kodi-test" "--gtest_filter=TestTagLoaderTagLib.SetGenre")
add_test(TestTagLoaderTagLib.SplitMBID "kodi-test" "--gtest_filter=TestTagLoaderTagLib.SplitMBID")
add_test(TestSwig.TypeConversion "kodi-test" "--gtest_filter=TestSwig.TypeConversion")
add_test(TestNfs.NfsFile "kodi-test" "--gtest_filter=NfsFile*")
add_test(TestZipManager.PathTraversal "kodi-test" "--gtest_filter=TestZipManager.PathTraversal")
add_test(TestZipFile.Read "kodi-test" "--gtest_filter=TestZipFile.Read")
add_test(TestZipFile.Exists "kodi-test" "--gtest_filter=TestZipFile.Exists")
add_test(TestZipFile.Stat "kodi-test" "--gtest_filter=TestZipFile.Stat")
add_test(TestZipFile.CorruptedFile "kodi-test" "--gtest_filter=TestZipFile.CorruptedFile")
add_test(TestFileFactory.Read "kodi-test" "--gtest_filter=TestFileFactory.Read")
add_test(TestFileFactory.Write "kodi-test" "--gtest_filter=TestFileFactory.Write")
add_test(TestFile.Read "kodi-test" "--gtest_filter=TestFile.Read")
add_test(TestFile.Write "kodi-test" "--gtest_filter=TestFile.Write")
add_test(TestFile.Exists "kodi-test" "--gtest_filter=TestFile.Exists")
add_test(TestFile.Stat "kodi-test" "--gtest_filter=TestFile.Stat")
add_test(TestFile.Delete "kodi-test" "--gtest_filter=TestFile.Delete")
add_test(TestFile.Rename "kodi-test" "--gtest_filter=TestFile.Rename")
add_test(TestFile.Copy "kodi-test" "--gtest_filter=TestFile.Copy")
add_test(TestFile.SetHidden "kodi-test" "--gtest_filter=TestFile.SetHidden")
add_test(TestDirectory.General "kodi-test" "--gtest_filter=TestDirectory.General")
add_test(TestDirectory.CreateRecursive "kodi-test" "--gtest_filter=TestDirectory.CreateRecursive")
add_test(TestAddonVersion.Constructor "kodi-test" "--gtest_filter=TestAddonVersion.Constructor")
add_test(TestAddonVersion.asString "kodi-test" "--gtest_filter=TestAddonVersion.asString")
add_test(TestAddonVersion.Equals "kodi-test" "--gtest_filter=TestAddonVersion.Equals")
add_test(TestAddonVersion.Equivalent "kodi-test" "--gtest_filter=TestAddonVersion.Equivalent")
add_test(TestAddonVersion.LessThan "kodi-test" "--gtest_filter=TestAddonVersion.LessThan")
add_test(TestAddonFactory.ShouldFailWhenAddonDoesNotHaveRequestedType "kodi-test" "--gtest_filter=TestAddonFactory.ShouldFailWhenAddonDoesNotHaveRequestedType")
add_test(TestAddonFactory.ShouldPickFirstExtensionWhenNotRequestingSpecificType "kodi-test" "--gtest_filter=TestAddonFactory.ShouldPickFirstExtensionWhenNotRequestingSpecificType")
add_test(TestAddonFactory.ShouldIgnoreMetadataExtension "kodi-test" "--gtest_filter=TestAddonFactory.ShouldIgnoreMetadataExtension")
add_test(TestAddonFactory.ShouldReturnDependencyInfoWhenNoExtensions "kodi-test" "--gtest_filter=TestAddonFactory.ShouldReturnDependencyInfoWhenNoExtensions")
add_test(TestAddonFactory.ShouldAcceptUnversionedDependencies "kodi-test" "--gtest_filter=TestAddonFactory.ShouldAcceptUnversionedDependencies")
add_test(TestAddonFactory.IconPathShouldBeBuiltFromPluginPath "kodi-test" "--gtest_filter=TestAddonFactory.IconPathShouldBeBuiltFromPluginPath")
add_test(TestAddonFactory.AssetsElementShouldOverrideImplicitArt "kodi-test" "--gtest_filter=TestAddonFactory.AssetsElementShouldOverrideImplicitArt")
add_test(AddonDatabaseTest.TestFindById "kodi-test" "--gtest_filter=AddonDatabaseTest.TestFindById")
add_test(AddonDatabaseTest.TestFindByNonExistingId "kodi-test" "--gtest_filter=AddonDatabaseTest.TestFindByNonExistingId")
add_test(TestAddonBuilder.ShouldFailWhenIdIsNotSet "kodi-test" "--gtest_filter=TestAddonBuilder.ShouldFailWhenIdIsNotSet")
add_test(TestAddonBuilder.ShouldBuildDependencyAddons "kodi-test" "--gtest_filter=TestAddonBuilder.ShouldBuildDependencyAddons")
add_test(TestAddonBuilder.ShouldReturnDerivedType "kodi-test" "--gtest_filter=TestAddonBuilder.ShouldReturnDerivedType")
add_test(TestUtil.GetQualifiedFilename "kodi-test" "--gtest_filter=TestUtil.GetQualifiedFilename")
add_test(TestUtil.MakeLegalPath "kodi-test" "--gtest_filter=TestUtil.MakeLegalPath")
add_test(TestUtil.SplitExec "kodi-test" "--gtest_filter=TestUtil.SplitExec")
add_test(TestUtil.MakeShortenPath "kodi-test" "--gtest_filter=TestUtil.MakeShortenPath")
add_test(TestURLGetWithoutUserDetails.URL "kodi-test" "--gtest_filter=URL*")
add_test(TestTextureUtils.SampleFiles "kodi-test" "--gtest_filter=SampleFiles*")
add_test(TestFileItemSpecifiedArtJpg.MovieFiles "kodi-test" "--gtest_filter=MovieFiles*")
add_test(TestFileItemFallbackArt.NoArt "kodi-test" "--gtest_filter=NoArt*")
add_test(TestFileItemBasePath.BaseNameMovies "kodi-test" "--gtest_filter=BaseNameMovies*")
subdirs("build/texturepacker")
subdirs("build/jsonschemabuilder")
subdirs("build/cores/RetroPlayer/messages")
subdirs("build/gtest")
subdirs("build/cores")
subdirs("build/cores/audioengine")
subdirs("build/cores/dll-loader")
subdirs("build/cores/dll-loader/exports")
subdirs("build/cores/dll-loader/exports/util")
subdirs("build/cores/externalplayer")
subdirs("build/cores/paplayer")
subdirs("build/cores/playercorefactory")
subdirs("build/drm")
subdirs("build/events")
subdirs("build/events/windows")
subdirs("build/kissfft")
subdirs("build/filesystem")
subdirs("build/filesystem/videodatabase")
subdirs("build/filesystem/musicdatabase")
subdirs("build/games")
subdirs("build/games/addons")
subdirs("build/games/addons/input")
subdirs("build/games/addons/streams")
subdirs("build/games/controllers")
subdirs("build/games/controllers/dialogs")
subdirs("build/games/controllers/guicontrols")
subdirs("build/games/controllers/types")
subdirs("build/games/controllers/windows")
subdirs("build/games/dialogs")
subdirs("build/games/dialogs/osd")
subdirs("build/games/ports")
subdirs("build/games/tags")
subdirs("build/games/windows")
subdirs("build/interfaces")
subdirs("build/interfaces/builtins")
subdirs("build/interfaces/generic")
subdirs("build/interfaces/info")
subdirs("build/interfaces/json-rpc")
subdirs("build/interfaces/json-rpc/schema")
subdirs("build/music")
subdirs("build/music/dialogs")
subdirs("build/music/infoscanner")
subdirs("build/music/jobs")
subdirs("build/music/tags")
subdirs("build/music/windows")
subdirs("build/network")
subdirs("build/network/websocket")
subdirs("build/peripherals")
subdirs("build/peripherals/addons")
subdirs("build/peripherals/bus")
subdirs("build/peripherals/bus/virtual")
subdirs("build/peripherals/devices")
subdirs("build/peripherals/dialogs")
subdirs("build/profiles")
subdirs("build/profiles/dialogs")
subdirs("build/profiles/windows")
subdirs("build/pvr")
subdirs("build/pvr/addons")
subdirs("build/pvr/channels")
subdirs("build/pvr/dialogs")
subdirs("build/pvr/epg")
subdirs("build/pvr/recordings")
subdirs("build/pvr/timers")
subdirs("build/pvr/windows")
subdirs("build/cores/RetroPlayer")
subdirs("build/cores/RetroPlayer/audio")
subdirs("build/cores/RetroPlayer/buffers")
subdirs("build/cores/RetroPlayer/buffers/video")
subdirs("build/cores/RetroPlayer/guibridge")
subdirs("build/cores/RetroPlayer/guicontrols")
subdirs("build/cores/RetroPlayer/guiplayback")
subdirs("build/cores/RetroPlayer/guiwindows")
subdirs("build/cores/RetroPlayer/playback")
subdirs("build/cores/RetroPlayer/process")
subdirs("build/cores/RetroPlayer/rendering")
subdirs("build/cores/RetroPlayer/rendering/VideoRenderers")
subdirs("build/cores/RetroPlayer/rendering/VideoShaders")
subdirs("build/cores/RetroPlayer/savestates")
subdirs("build/cores/RetroPlayer/streams")
subdirs("build/cores/RetroPlayer/streams/memory")
subdirs("build/settings")
subdirs("build/settings/dialogs")
subdirs("build/settings/lib")
subdirs("build/settings/windows")
subdirs("build/xbmc")
subdirs("build/addons")
subdirs("build/addons_binary-addons")
subdirs("build/addons_interfaces")
subdirs("build/addons_interfaces_addon")
subdirs("build/addons_interfaces_gui")
subdirs("build/addons_interfaces_gui_controls")
subdirs("build/addons_interfaces_gui_dialogs")
subdirs("build/addons_kodi-addon-dev-kit_include_kodi")
subdirs("build/addons_kodi-addon-dev-kit_include_kodi_addon-instance")
subdirs("build/addons_kodi-addon-dev-kit_include_kodi_gui")
subdirs("build/addons_kodi-addon-dev-kit_include_kodi_gui_controls")
subdirs("build/addons_kodi-addon-dev-kit_include_kodi_gui_dialogs")
subdirs("build/addons_kodi-addon-dev-kit_include_kodi_tools")
subdirs("build/addons_settings")
subdirs("build/commons")
subdirs("build/dbwrappers")
subdirs("build/dialogs")
subdirs("build/favourites")
subdirs("build/guilib")
subdirs("build/guilib_guiinfo")
subdirs("build/input")
subdirs("build/input/actions")
subdirs("build/input/joysticks")
subdirs("build/input/joysticks/dialogs")
subdirs("build/input/joysticks/generic")
subdirs("build/input/joysticks/keymaps")
subdirs("build/input/keyboard")
subdirs("build/input/keyboard/generic")
subdirs("build/input/mouse")
subdirs("build/input/mouse/generic")
subdirs("build/listproviders")
subdirs("build/media")
subdirs("build/messaging")
subdirs("build/messagingHelpers")
subdirs("build/pictures")
subdirs("build/platform")
subdirs("build/playlists")
subdirs("build/powermanagement")
subdirs("build/programs")
subdirs("build/rendering")
subdirs("build/storage")
subdirs("build/threads")
subdirs("build/utils")
subdirs("build/view")
subdirs("build/weather")
subdirs("build/windowing")
subdirs("build/windows")
subdirs("build/test")
subdirs("build/test/addons")
subdirs("build/test/filesystem")
subdirs("build/test/python")
subdirs("build/test/music_tags")
subdirs("build/test/network")
subdirs("build/test/playlists")
subdirs("build/test/threads")
subdirs("build/test/utils")
subdirs("build/test/video")
subdirs("build/test/audioengine_sinks")
subdirs("build/video")
subdirs("build/video/dialogs")
subdirs("build/video/jobs")
subdirs("build/video/tags")
subdirs("build/video/windows")
subdirs("build/cores/VideoPlayer")
subdirs("build/cores/VideoPlayer/codecs")
subdirs("build/cores/VideoPlayer/codecs/audio")
subdirs("build/cores/VideoPlayer/codecs/overlay")
subdirs("build/cores/VideoPlayer/codecs/video")
subdirs("build/cores/VideoPlayer/demuxers")
subdirs("build/cores/VideoPlayer/inputstreams")
subdirs("build/cores/VideoPlayer/subtitles")
subdirs("build/cores/VideoPlayer/process")
subdirs("build/cores/VideoPlayer/videorenderers")
subdirs("build/cores/VideoPlayer/videorenderers/shaders")
subdirs("build/cores/VideoPlayer/videorenderers/hwdec")
subdirs("build/platform/posix")
subdirs("build/platform/posix/filesystem")
subdirs("build/platform/posix/utils")
subdirs("build/platform/linux")
subdirs("build/platform/linux/input")
subdirs("build/platform/linux/network")
subdirs("build/platform/linux/peripherals")
subdirs("build/platform/linux/powermanagement")
subdirs("build/platform/linux/storage")
subdirs("build/input/touch")
subdirs("build/input/touch/generic")
subdirs("build/cores/RetroPlayer/process/rbpi")
subdirs("build/cores/VideoPlayer/Process/rbpi")
subdirs("build/windowing/linux")
subdirs("build/windowing/X11")
subdirs("build/cores/RetroPlayer/process/X11")
subdirs("build/cores/VideoPlayer/Process/X11")
subdirs("build/cdrip")
subdirs("build/network/dacp")
subdirs("build/mdns")
subdirs("build/rendering/gl")
subdirs("build/interfaces/legacy")
subdirs("build/interfaces/legacy/wsgi")
subdirs("build/interfaces/python")
subdirs("build/swig")
subdirs("build/upnp")
subdirs("build/network/upnp")
subdirs("build/network/httprequesthandler")
subdirs("build/network/httprequesthandler/python")
